# For more information: https://laravel.com/docs/sail
version: '3'
services:
  laravel.test:
    build:
      context: ./docker/8.0
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.0/app
    container_name: footballgram-laravel
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
    volumes:
      - '.:/var/www/html'
      - './docker/8.0/start-container:/usr/local/bin/start-container'
      - './docker/8.0/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf'
    networks:
      - sail
    depends_on:
      - mysql
      - redis
      - selenium
  webserver:
    image: nginx:alpine
    container_name: footballgram-webserver
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - ./:/var/www
      - ./docker/nginx/footballgram.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./storage/app/public/images:/opt/laravel/storage/
    networks:
      - sail
    depends_on:
      - laravel.test
  mysql:
    image: 'mysql:8.0'
    container_name: footballgram-mysql
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'sailmysql:/var/lib/mysql'
      - './database/backups:/docker-entrypoint-initdb.d'
    networks:
      - sail
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
  redis:
    image: 'redis:alpine'
    container_name: footballgram-redis
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'sailredis:/data'
    networks:
      - sail
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
  meilisearch:
    image: 'getmeili/meilisearch:latest'
    container_name: footballgram-melisearch
    ports:
      - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    volumes:
      - 'sailmeilisearch:/data.ms'
    networks:
      - sail
  mailhog:
    image: 'mailhog/mailhog:latest'
    container_name: footballgram-mailhog
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - sail
  selenium:
    image: 'selenium/standalone-chrome'
    container_name: footballgram-selenium
    volumes:
      - '/dev/shm:/dev/shm'
    networks:
      - sail
  phpmyadmin:
    image: phpmyadmin
    container_name: footballgram-phpmyadmin
    ports:
      - "81:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  sailmysql:
    driver: local
  sailredis:
    driver: local
  sailmeilisearch:
    driver: local
