<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateLeaguesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('premier_league_table', function (Blueprint $table) {
            $table->string('name');
            $table->integer('position')
                  ->default(0);
            $table->integer('played')
                  ->default(0);
            $table->integer('won')
                  ->default(0);
            $table->integer('drawn')
                  ->default(0);
            $table->integer('lost')
                  ->default(0);
            $table->integer('goals_for')
                  ->default(0);
            $table->integer('goals_against')
                  ->default(0);
            $table->integer('goals_difference')
                  ->default(0);
            $table->integer('points')
                  ->default(0);
            $table->timestamp('updated_at');
            $table->string('season');
        });
        Schema::create('calcio_table', function (Blueprint $table) {
            $table->string('name');
            $table->integer('position')
                  ->default(0);
            $table->integer('played')
                  ->default(0);
            $table->integer('won')
                  ->default(0);
            $table->integer('drawn')
                  ->default(0);
            $table->integer('lost')
                  ->default(0);
            $table->integer('goals_for')
                  ->default(0);
            $table->integer('goals_against')
                  ->default(0);
            $table->integer('goals_difference')
                  ->default(0);
            $table->integer('points')
                  ->default(0);
            $table->timestamp('updated_at');
            $table->string('season');
        });
        Schema::create('laliga_table', function (Blueprint $table) {
            $table->string('name');
            $table->integer('position')
                  ->default(0);
            $table->integer('played')
                  ->default(0);
            $table->integer('won')
                  ->default(0);
            $table->integer('drawn')
                  ->default(0);
            $table->integer('lost')
                  ->default(0);
            $table->integer('goals_for')
                  ->default(0);
            $table->integer('goals_against')
                  ->default(0);
            $table->integer('goals_difference')
                  ->default(0);
            $table->integer('points')
                  ->default(0);
            $table->timestamp('updated_at');
            $table->string('season');
        });
        Schema::create('bundesliga_table', function (Blueprint $table) {
            $table->string('name');
            $table->integer('position')
                  ->default(0);
            $table->integer('played')
                  ->default(0);
            $table->integer('won')
                  ->default(0);
            $table->integer('drawn')
                  ->default(0);
            $table->integer('lost')
                  ->default(0);
            $table->integer('goals_for')
                  ->default(0);
            $table->integer('goals_against')
                  ->default(0);
            $table->integer('goals_difference')
                  ->default(0);
            $table->integer('points')
                  ->default(0);
            $table->timestamp('updated_at');
            $table->string('season');
        });
        Schema::create('khaligefars_table', function (Blueprint $table) {
            $table->string('name');
            $table->integer('position')
                  ->default(0);
            $table->integer('played')
                  ->default(0);
            $table->integer('won')
                  ->default(0);
            $table->integer('drawn')
                  ->default(0);
            $table->integer('lost')
                  ->default(0);
            $table->integer('goals_for')
                  ->default(0);
            $table->integer('goals_against')
                  ->default(0);
            $table->integer('goals_difference')
                  ->default(0);
            $table->integer('points')
                  ->default(0);
            $table->timestamp('updated_at');
            $table->string('season');
        });
        Schema::create('loshampione_table', function (Blueprint $table) {
            $table->string('name');
            $table->integer('position')
                  ->default(0);
            $table->integer('played')
                  ->default(0);
            $table->integer('won')
                  ->default(0);
            $table->integer('drawn')
                  ->default(0);
            $table->integer('lost')
                  ->default(0);
            $table->integer('goals_for')
                  ->default(0);
            $table->integer('goals_against')
                  ->default(0);
            $table->integer('goals_difference')
                  ->default(0);
            $table->integer('points')
                  ->default(0);
            $table->timestamp('updated_at');
            $table->string('season');
        });
        Schema::create('azadegan_table', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->integer('position')
                  ->default(0);
            $table->integer('played')
                  ->default(0);
            $table->integer('won')
                  ->default(0);
            $table->integer('drawn')
                  ->default(0);
            $table->integer('lost')
                  ->default(0);
            $table->integer('goals_for')
                  ->default(0);
            $table->integer('goals_against')
                  ->default(0);
            $table->integer('goals_difference')
                  ->default(0);
            $table->integer('points')
                  ->default(0);
            $table->timestamp('updated_at');
            $table->string('season');
        });
        Schema::create('eredivisie_table', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->integer('position')
                  ->default(0);
            $table->integer('played')
                  ->default(0);
            $table->integer('won')
                  ->default(0);
            $table->integer('drawn')
                  ->default(0);
            $table->integer('lost')
                  ->default(0);
            $table->integer('goals_for')
                  ->default(0);
            $table->integer('goals_against')
                  ->default(0);
            $table->integer('goals_difference')
                  ->default(0);
            $table->integer('points')
                  ->default(0);
            $table->timestamp('updated_at');
            $table->string('season');
        });
        Schema::create('stars_league_table', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->integer('position')
                  ->default(0);
            $table->integer('played')
                  ->default(0);
            $table->integer('won')
                  ->default(0);
            $table->integer('drawn')
                  ->default(0);
            $table->integer('lost')
                  ->default(0);
            $table->integer('goals_for')
                  ->default(0);
            $table->integer('goals_against')
                  ->default(0);
            $table->integer('goals_difference')
                  ->default(0);
            $table->integer('points')
                  ->default(0);
            $table->timestamp('updated_at');
            $table->string('season');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('premier_league_table');
        Schema::dropIfExists('calcio_table');
        Schema::dropIfExists('laliga_table');
        Schema::dropIfExists('bundesliga_table');
        Schema::dropIfExists('khaligefars_table');
        Schema::dropIfExists('loshampione_table');
        Schema::dropIfExists('azadegan_table');
        Schema::dropIfExists('eredivisie_table');
        Schema::dropIfExists('stars_league_table');
    }
}
